name: justitis_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  appwrite: ^9.0.1
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  firebase_messaging_web: ^3.5.7
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.5
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  intl: ^0.18.1
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  responsive_framework: ^1.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/menu/
